version: '3'
services:
  dockerhub:
    image: maccyber/micro-dockerhub-hook
    # build: .
    environment:
      - TOKEN=b98ebdd3-5319-432e-a1e4-a131c62555f3
    ports:
      - "8888:3000"
    volumes:
      - ./scripts:/src/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
networks:
  default:
    external:
      name: local_service
